### PR TITLE
chore: AppBenchmark Sample - Update to net6

### PR DESCRIPTION
**Pull request by aesteves900**

### CODE REVIEW

**Comment by aesteves900** [comment]
@nickrandolph , about the WASM platform I got a PlatformNotSuportedException, is there anything we can do?

// Validating benchmarks:
Assembly AppBenchmark.Wasm which defines benchmarks is non-optimized
Benchmark was built without optimization enabled (most probably a DEBUG configuration). Please, build it in RELEASE.
If you want to debug the benchmarks, please see https://benchmarkdotnet.org/articles/guides/troubleshooting.html#debugging-benchmarks.
No column providers defined, result table will be empty.
// ***** BenchmarkRunner: Start   *****
// ***** Found 3 benchmark(s) in total *****
// ***** Building 1 exe(s) in Parallel: Start   *****
// ***** Done, took 00:00:00 (0.09 sec)   *****
// Found 3 benchmarks:
//   TryFinallyBenchmark.SingleCall: InProcess(Toolchain=InProcessEmitToolchain, IterationCount=5, LaunchCount=1, WarmupCount=1)
//   TryFinallyBenchmark.WithTryFinallyOneMethod: InProcess(Toolchain=InProcessEmitToolchain, IterationCount=5, LaunchCount=1, WarmupCount=1)
//   TryFinallyBenchmark.WithTryFinallyTwoMethods: InProcess(Toolchain=InProcessEmitToolchain, IterationCount=5, LaunchCount=1, WarmupCount=1)

// **************************
// Benchmark: TryFinallyBenchmark.SingleCall: InProcess(Toolchain=InProcessEmitToolchain, IterationCount=5, LaunchCount=1, WarmupCount=1)
// *** Execute ***
// Launch: 1 / 1
// * Artifacts cleanup *
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Threading.Thread.ThrowIfNoThreadStart(Boolean internalThread) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\Thread.cs:line 176
   at System.Threading.Thread.Start(Boolean captureContext, Boolean internalThread) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\Thread.cs:line 250
   at System.Threading.Thread.Start() in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\Thread.cs:line 232
   at BenchmarkDotNet.Toolchains.InProcess.Emit.InProcessEmitExecutor.Execute(ExecuteParameters executeParameters)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunExecute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver, IDiagnoser diagnoser, Int32 launchIndex)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Execute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunCore(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, IResolver resolver, BuildResult buildResult)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String resultsFolderPath, String logFilePath, Int32 totalBenchmarkCount, StartedClock& runsChronometer, Int32& benchmarksToRunCount)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
   at BenchmarkDotNet.Running.BenchmarkRunner.RunWithDirtyAssemblyResolveHelper(Type type, IConfig config, String[] args)
   at BenchmarkDotNet.Running.BenchmarkRunner.<>c__DisplayClass1_0.<Run>b__0()
   at BenchmarkDotNet.Running.BenchmarkRunner.RunWithExceptionHandling(Func`1 run)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(Type type, IConfig config, String[] args)
   at AppBenchmark.BenchmarkDotNetControl.Run() in C:\Projetcs\Uno.Samples\UI\Benchmark\AppBenchmark\AppBenchmark.Shared\BenchmarkDotNetControl.xaml.cs:line 70


image

**Comment by nickrandolph** [comment]
@aesteves900 I've corrected the sample to use the uno.benchmark for each of the targets (see the [README](https://github.com/unoplatform/Uno.Samples/blob/61328eb0254e1a78db03f1dfa7853e328c4e18d2/UI/Benchmark/README.md)).
Please add the missing uno targets (wpf/gtk/linux etc)

**Comment by aesteves900** [comment]
> @aesteves900 I've corrected the sample to use the uno.benchmark for each of the targets (see the [README](https://github.com/unoplatform/Uno.Samples/blob/61328eb0254e1a78db03f1dfa7853e328c4e18d2/UI/Benchmark/README.md)). Please add the missing uno targets (wpf/gtk/linux etc)

The WPF, GTK, and Linus are not part of the original solution. I believe the Benchmark library doesn't work for GTK and Linux. Could you create an issue for that?

**Comment by nickrandolph** [comment]
Ok, I've created an issue and we can move this PR forward

**Review by nickrandolph — APPROVED** [review]

**Pull request merged**
