### PR TITLE
chore: CameraCaptureUI Sample - Update to net6

### PR DESCRIPTION
**Pull request by aesteves900**

### CODE REVIEW

**Comment by aesteves900** [comment]
@nickrandolph , In my understanding on WinUI3 the cameraUI is not ready to use.

https://github.com/microsoft/WindowsAppSDK/issues/1034#issuecomment-1243314839

**Comment by nickrandolph** [comment]
Testing Android throws exception when attempting to capture photo:
   at System.Uri.get_LocalPath()
   at Windows.Media.Capture.CameraCaptureUI.CaptureFile(CancellationToken ct, CameraCaptureUIMode mode) in C:\a\1\s\src\Uno.UWP\Media\Capture\CameraCaptureUI.Android.cs:line 56
   at Windows.Foundation.AsyncOperation`1.<BuildTaskAsync>d__5[[Windows.Storage.StorageFile, Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].MoveNext() in C:\a\1\s\src\Uno.Foundation\AsyncOperation.TResult.cs:line 47
   at System.WindowsRuntimeSystemExtensions.<AsTaskCore>d__11`1[[Windows.Storage.StorageFile, Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].MoveNext() in C:\a\1\s\src\Uno.UWP\System.Runtime\WindowsRuntimeSystemExtensions.cs:line 66
   at CameraCaptureUISample.MainPage.button_Click(Object sender, RoutedEventArgs e) in C:\source\github\unoplatform\Uno.Samples\UI\CameraCaptureUI\CameraCaptureUISample\CameraCaptureUISample.Shared\MainPage.xaml.cs:line 41

**Comment by nickrandolph** [comment]
Related issue: https://github.com/unoplatform/Uno.Samples/issues/280

**Comment by nickrandolph** [comment]
Related issue: https://github.com/unoplatform/Uno.Samples/issues/281

**Review by nickrandolph — APPROVED** [review]

**Pull request merged**
