### PR TITLE
docs: TheCatApiClient sample app

### PR DESCRIPTION
**Pull request by darenm**
A sample app that compliments the web services how-to being created based upon issue: https://github.com/unoplatform/uno/issues/1636

### CODE REVIEW

**Comment by darenm** [comment]
I just noticed that the .vsts-ci/yml assumes that the samples are all in the UI folder... I added a new folder. What is the preference here?
* Move the sample to UI (easiest!)
* Update the CI task

**Review by jeromelaban — COMMENTED** [review]
Looks good to me! 

@ebariche can you take a look as well ?

**Comment by ebariche** [comment]
@darenm, good sample !

Could you bump the sample to 3.1.6 (Uno.UI/Uno.UI.RemoteControl/Uno.UI.WebAssembly) and add your sample to the list in https://github.com/unoplatform/Uno.Samples/blob/master/README.md ?

**Comment by darenm** [comment]
@ebarich Certainly!

**Comment by ebariche** [comment]
Purr-fect !

**Review by ebariche — APPROVED** [review]

**Pull request merged**
