### PR TITLE
chore(SkiaSharpTest): Migrating WpfHost in SkiaSharpTest

### PR DESCRIPTION
**Pull request by lindexi**
Fix the running error as:

> If you are seeing this, make sure to follow the "Migrating WpfHost" section of Migrating from previous releases article in the Uno Platform documentation at https://aka.platform.uno/uno5-wpfhost-migration. WpfHost is used at the application level instead of window level starting Uno Platform 5.0.

### CODE REVIEW

**Comment by lindexi** [comment]
@jeromelaban Can I ask any update here?

**Comment by jeromelaban** [comment]
@lindexi Apologies for the delay. we'll likely update that sample to use single project, which won't use that structure anymore.

Let's try a rebuild to be sure.

**Comment by lindexi** [comment]
@jeromelaban What should I do? Thank you.

**Review by jeromelaban — APPROVED** [review]
The build looks good, let's merge as is :) @Kunal22shah may change the structure later one as it gets migrated to single-project.

**Pull request merged**
