### PR TITLE
Adds PhotoViewer sample with ZoomContentControl

### LINKED ISSUE #649: Add PhotoViewer sample
Add a sample that demonstrates a simple photoviewer application that allows the user to zoom, pan (touch/mouse) and scroll the image. 
Basic mouse interactions should be:
- Mouse wheel - pans up/down
- Mouse wheel + Ctrl - zooms in/out
- Mouse wheel + Shift - pans left/right
- Press Mouse wheel and move mouse - pan any direction

### PR DESCRIPTION
**Pull request by iurycarlos**
Closes #649

### CODE REVIEW

**Comment by iurycarlos** [comment]
Things are missing:

- ScrollBars are not working propperly. It seems a bug at winui/uno side.
- I started the sample as just a sample for the control, but we can create another branch as a PhotoViewerSample

**Comment by agneszitte** [comment]
@iurycarlos don't forget to add a proper ReadMe for the sample that you are adding.
We are starting to adjust the sample with a better structure (https://github.com/unoplatform/uno.samples-private/issues/145)

**Comment by nickrandolph** [comment]
@agneszitte I suggested to @iurycarlos to use the existing structure for now and we can update to single project once we have this PR merged

**Comment by nickrandolph** [comment]
> Things are missing:
> 
> * ScrollBars are not working propperly. It seems a bug at winui/uno side.
> * I started the project as just a sample for the control, but we can create another branch as a PhotoViewerSample

Let's do any restructuring (eg PhotoViewerSample) as part of this initial commit

**Review by nickrandolph — APPROVED** [review]

**Comment by agneszitte** [comment]
> - @iurycarlos don't forget to add a proper ReadMe for the sample that you are adding.
We are starting to adjust the samples with a better structure https://github.com/unoplatform/uno.samples-private/issues/145
> - @agneszitte I suggested to @iurycarlos to use the existing structure for now and we can update to single project once we have this PR merged

@nickrandolph and @iurycarlos I was talking about the fact that when adding a new sample to Uno.Samples repo we need to make sure it is part of the list of the samples in the [main ReadMe](https://github.com/unoplatform/Uno.Samples/blob/master/README.md) of the repo + having a dedicated ReadMe file directly at the root of the sample folder with more details and screenshots as needed [like here for example](https://github.com/unoplatform/Uno.Samples/blob/master/UI/MauiEmbedding/SyncfusionApp/ReadMe.md)

**Pull request merged**
